### ISSUE TITLE
cljfmt options

### ISSUE THREAD

**Issue by martinklepsch** [snoe/node-cljfmt#1]
Would be nice to be able to pass the options you can pass to the cljfmt lein plugin as well: https://github.com/weavejester/cljfmt#configuration

Maybe this could be done as a simple `edn` file that can be supplied via an optional command line argument.

Nice lib 👍

**Comment by snoe** [comment]
Thanks, 0.4.1-1 now supports this.

**Comment by martinklepsch** [comment]
@snoe wow, that was quick, thanks a ton! 👍
